# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    http_client:
        scoped_clients:
            mailer.client:
                base_uri: '%env(MICROSERVICE_MAILER_URL)%'
                headers:
                    X-Microservice-Token: '%env(MICROSERVICE_MAILER_TOKEN)%'
                    Content-Type: application/json
                timeout: 5

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
