<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Creates the user_quest_completion table for the daily/weekly quest system.
 */
final class Version20260518100001 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user_quest_completion table';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE user_quest_completion (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                user_id INT NOT NULL,
                quest_code VARCHAR(64) NOT NULL,
                period_key VARCHAR(16) NOT NULL,
                xp_awarded INT NOT NULL,
                claimed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_UQC_USER ON user_quest_completion (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_user_quest_period ON user_quest_completion (user_id, quest_code, period_key)');
        $this->addSql(
            'ALTER TABLE user_quest_completion ADD CONSTRAINT FK_UQC_USER '.
            'FOREIGN KEY (user_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE'
        );
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE user_quest_completion DROP CONSTRAINT FK_UQC_USER');
        $this->addSql('DROP TABLE user_quest_completion');
    }
}
